export const DEFAULTS = {
  roomHeightInches: 96,
  wallThicknessInches: 4,
  minClearanceInches: 24,
  doorWidthInches: 32,
  windowHeightInches: 48,
  gridSnapInches: 6,
  defaultUnit: 'inches',
  defaultScale: 4.0,
  colors: {
    sofa: '#c8a97e',
    loveseat: '#d4b48c',
    bed: '#a8c4d4',
    desk: '#d4c87a',
    bookshelf: '#8c6444',
    dining_table: '#b89870',
    coffee_table: '#c9a96e',
    dresser: '#b8a090',
    nightstand: '#c4b0a0',
    armchair: '#d0b888',
    tv_stand: '#909090',
    cabinet: '#a09080',
    default: '#cccccc',
  },
  validation: {
    allowOverlap: false,
    allowOutOfBounds: false,
    snapToGrid: true,
    warnNarrowPath: true,
  },
  llm: {
    defaultModel: process.env.OPENAI_MODEL || 'gpt-5.3-codex',
    fallbackModel: process.env.OPENAI_MODEL || 'gpt-5.3-codex',
    maxTokens: 2048,
    temperature: 0.3,
  },
  export: {
    schemaVersion: '1.0',
    defaultFormat: 'json',
  },
};

export const FURNITURE_BOUNDS = {
  sofa: { minW: 60, maxW: 120, minD: 30, maxD: 50 },
  loveseat: { minW: 48, maxW: 72, minD: 28, maxD: 42 },
  bed_twin: { minW: 36, maxW: 42, minD: 72, maxD: 80 },
  bed_full: { minW: 52, maxW: 58, minD: 72, maxD: 80 },
  bed_queen: { minW: 58, maxW: 64, minD: 78, maxD: 84 },
  bed_king: { minW: 74, maxW: 80, minD: 78, maxD: 84 },
  desk: { minW: 36, maxW: 72, minD: 20, maxD: 36 },
  dining_table: { minW: 36, maxW: 96, minD: 30, maxD: 48 },
  bookshelf: { minW: 24, maxW: 48, minD: 8, maxD: 16 },
  dresser: { minW: 30, maxW: 60, minD: 16, maxD: 24 },
};
